spring.profiles.active=dev
spring.application.name=employee-management-system

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET:mySecretKeyForDevelopmentPurposeOnlyMustBeAtLeast256BitsLong!!}
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# Logging
logging.level.com.hari.employeemanagement=DEBUG
logging.level.org.springframework.security=DEBUG
